# -*- coding: utf-8 -*-
"""Ejercicios

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F3U_0ogfz27I1AJHO0Yy6kreFNphvOb8

# 1 ejercicio
"""

def solicitud():
  primer_nombre = input("Ingrese su primer nombre: ")
  no1 = str("no")
  segundo_nombre = str(input("Ingrese su segundo nombre, si no tiene ponga no: "))
  primer_apellido = input("Ingrese su su primer appellido: ")
  segundo_apellido = input("Ingrese su asu segundo appellido: ")
  edad = input("ingrese su edad: ")
  dirección = input("ingrese su dirección de residencia: ")
  return f"Usted se llama {primer_nombre} {segundo_nombre}"

solicitud()

def solicitud():
  primer_nombre = input("Ingrese su primer nombre: ")
  segundo_nombre = str(input("Ingrese su segundo nombre, si no tiene ponga no: "))
  primer_apellido = str(input("Ingrese su su primer appellido, si no tiene ponga no: "))
  segundo_apellido = str(input("Ingrese su su segundo appellido, si no tiene ponga no: "))
  edad = input("ingrese su edad: ")
  d1 = str(input("ingrese su dirección de residencia, calle ponga no: "))
  d2 = str(input("ingrese su dirección de residencia, carrera ponga no: "))
  d3 = str(input("ingrese su dirección de residencia, si vive en apartamento, de lo contrario ponga no: "))
  no1 = str("no")
  if segundo_nombre == no1:
    print("Su información es" , primer_nombre , primer_apellido ,  segundo_apellido, edad)
  elif primer_apellido == no1:
    print("Su información es" , primer_nombre ,  segundo_apellido, edad)
  elif segundo_apellido == no1:
    print("Su información es" , primer_nombre  ,   edad)
  elif d1 == no1:
    print("Su información es" , primer_nombre  , edad, d2, d3 )
  elif d2 == no1:
    print("Su información es" , primer_nombre  , edad, d1, d3 )
  elif d3 == no1:
    print("Su información es" , primer_nombre   , edad, d2, d3 )
  else: 
    print("su informacion es: " , primer_nombre ,segundo_nombre, primer_apellido ,  segundo_apellido, edad, d1, d2, d3)
  return

solicitud()

def solicitud():
  primer_nombre = input("Ingrese su primer nombre: ")
  segundo_nombre = str(input("Ingrese su segundo nombre, si no tiene ponga no: "))
  primer_apellido = str(input("Ingrese su su primer appellido ponga no: "))
  segundo_apellido = str(input("Ingrese su asu segundo appellido ponga no: "))
  edad = input("ingrese su edad: ")
  d1 = str(input("ingrese su dirección de residencia, calle ponga no: "))
  d2 = str(input("ingrese su dirección de residencia, carrera ponga no: "))
  d3 = str(input("ingrese su dirección de residencia, si vive en apartamento, de lo contrario ponga no: "))
  no1 = str("no")
  if segundo_nombre == no1 and primer_apellido == no1 and segundo_apellido == no1 and d1 == no1 and d2 == no1 and d3 == no1:
    print("Su información es: " , primer_nombre , primer_apellido ,  segundo_apellido, edad, d1, d2, d3 )
  else:
    print("Su información es: " , primer_nombre , segundo_nombre , primer_apellido ,  segundo_apellido, edad, d1, d2, d3 )

solicitud()

def nombre():
  nombre = input("ingrese su nombre")
  print("Hola" , nombre)

nombre()

def base():
  lado_1 = int(input("Ingrese un lado del cuadrado: "))
  lado_2 = int(input("Ingrese el otro lado del cuadrado: "))
  area = lado_1 * lado_2
  print("El area del cuadrado es: ", area)

base()

def rectangulo():
  lado_1 = int(input("Ingrese un lado del cuadrado: "))
  lado_2 = int(input("Ingrese el otro lado del cuadrado: "))
  area = lado_1 * lado_2
  print("El area del rectangulo es : ", area)

rectangulo()

def triangulo():
  base = int(input("Ingrese la base del renftangulo: "))
  altura = int(input("Ingrese el otro lado del cuadrado: "))
  area = ((base*altura)/2)
  print("El area del triangulo es: ", area)

triangulo()

print("asdas asdasdsa asdasda asdasd \n adsadasd \n asdsad")

def reciclaje():
  b1 = int(1000)
  b2 = int(2000)
  b3 = int(3000)
  l1 = int(1)
  l2 = int(2)
  l3 = int(3)
  print("Lista de tamaño de botella y el dinero que recibira: \n 1) Por unidad de botella de 1 litro recibira: 1000 \n 2) Por unidad de botella de 1.5 litros recibira: 2000 \n 3) Por unidad de botella de 2 litro recibira: 3000 \n  ")
  ing = int(input("Por favor eliga un número de la lista que corresponda a la botella que va a reciclar: "))
  cad = int(input("cuantas botellas va a ingresar: "))
  if l1 == ing:
    print("Usted ingreso: " , cad ," botella(s) de 1 litro, su pago es: ", (b1*cad))
  elif l2 == ing:
    print("Usted ingreso: " , cad ," botella(s) de 1.5 litros, su pago es: ", (b2*cad))
  else:
    print("Usted ingreso: " , cad ," botella(s) de 2 litros, su pago es: ", (b3*cad))

reciclaje()



def comida():
  comida = int(input("ingrese el costo de su comida: "))
  propina = int(input("propina: "))
  iva = (comida*0.08)
  valor = iva + propina

  print("valor de su comida con el impuesto es: " , iva , " valor totar a pagar mas su propina es", valor)

comida()

def peso():
  peso_a = float(123)
  peso_b = float(35)
  a = int(input("Cuantos unidades del prducto a desea: "))
  b = int(input("Cuantos unidades del producto b desea: "))
  total = (((peso_a * a) + (peso_b * b)))
  if total%2 == 0:
    print("puede vender", total)
  else:
    print("Su peso total es: ", total , "pero no puede vender si la suma del peso no es par")

peso()

carro = float(70)
motos = float(42)
bicileta = float(10)
c1 = int(1)
m2 = int(2)
b3 = int(3)
parking = int(input("indique en que llego, si es carro marque 1, si es moto marque 2, si es bicilitea marque 3: "))
tiempo = int(input("cuanto tiempo estuvo: "))
if c1 == parking:
  print("Su valor total es: ", (tiempo*carro))
  dinero = int(input("ingrese la cantidad de dinero: "))
  print("Su cambio es: ", (dinero-(tiempo*carro)))
elif m2 == parking:
  print("su valor total es: ", (tiempo*motos))
  dinero = int(input("ingrese la cantidad de dinero: "))
  print("Su cambio es: ", (dinero-(tiempo*motos)))
else:
  print("su valor total", (tiempo*bicileta))
  dinero = int(input("ingrese la cantidad de dinero: "))
  print("Su cambio es: ", (dinero-(tiempo*bicileta)))

def circulo():
  pi = float(3.1415927)
  r = float(input("Ingrese el radio del ciruclo para calcular el area y el perimitro: "))
  area = (pi *(r ** 2))
  peri = (2 * pi * r)
  print("el area del circulo es: ", area , " cm al cuadrado. \n Su perimitro es: ", peri)

circulo()

def cumplido():
  ano = int(input("En que año nacio: "))
  mes = int(input("En que mes nacio: "))
  dia = int(input("En que día nacion: "))
  ano1 = int(input("Ingrese el año actual: "))
  mes1 = int(input("Ingrese el mes actual: "))
  dia1 = int(input("Ingrese el día actual: "))
  print("Su edad actual es: ",  (ano1 - ano), "años, meses: ", (mes1 - mes), " y día: ",(dia1 - dia))

cumplido()

def grados():
  gc = int(input("Ingrese la temperatura atual en grados celcius para hacer la conversion a fahrenheit y en grados kelvin"))
  f = (( gc * 1.8) + 32)
  k = (gc + 273.15)
  print("Usted ingreso " , gc , "en grados celcius, la conersión es la siguiente: \n A Fahrenheit: ", f , "\n A Kelvin: " , k)

grados()

def nume():
  mi_lista5 = [1 , 265, 23, 4, 15, 45, 7, 8, 9, 10]
  for i in mi_lista5:
    maximo = max(mi_lista5)
    minimo = min(mi_lista5)
    print(("El valor maximo de la lista es: ", maximo , "el valor minimo es: ", minimo ,""))

nume()



for i in range (1,11,1):
  print(i)

def lista1():
  for i in range (1,11,1):
    print(i)

lista1()

def nume():
  mi_lista5 = [1 , 265, 23, 4, 15, 45, 7, 8, 9, 10]
  maximo = max(mi_lista5)
  minimo = min(mi_lista5)
  print(("El valor maximo de la lista es: ", maximo , "el valor minimo es: ", minimo ,"suma de la lista: " , sum(mi_lista5)))

nume()

def nume1():
  lista = input("Ingrese dos numeros, porfavor con espacio: ")
  print(lista)
  lista1 = lista.split()
  print(lista1)
  lista1 = [int(i) for i in lista1]
  print(lista1)
  print(f"El valor maximo de la lista es: ", max(lista1) , "el valor minimo es: ", min(lista1) ,"suma de la lista: " , sum(lista1))

nume1()

u = str(input("Ingrese el mes para saber cuantos días tiene"))
if u == "enero":
  print(31)
elif u == "febrero":
  print(28)
elif u == "marzo":
  print(31)
elif u == "abril":
  print(30)
elif u == "mayo":
  print(31)
elif u == "junio":
  print(30)
elif u == "julio":
  print(31)
elif u == "agosto":
  print(31)
elif u == "septiembre":
  print(30)
elif u == "octubre":
  print(31)
elif u == "novienbre":
  print(30)
elif u == "diciembre":
  print(31)

def edad():
  edad1 = int(input("ingrese su edad: "))
  if edad1 < 18:
    print("MENOR DE EDAD")
  elif edad1 >= 18 and edad1 < 45:
    print("MAYOR DE EDAD")
  elif edad1 >= 45 and edad1 < 60:
    print("ADULTOO")
  else:
    print("Adulto Mayoor")

edad()

def dinero():
  print("Lista actual de los billetes colombianos: \n 1) Billete de 2 mil\n 2) Billete de 5 mil \n 3) Billete de 10 mil \n 4) Billete de 20 mil \n 5) Billete de 50 mil \n 6) Billete de 100 mil")
  bi = str(input("Introduzca un billete y coloque el número correspondiente con el \n billete que recien ingreso: "))
  if bi == "1":
    print("En el anverso se aprecia la imagen de la artista Débora Arango")
  elif bi == "2":
    print("En el anverso se aprecia la imagen del poeta José Asunción Silva")
  elif bi == "3":
    print("En el anverso se aprecia la imagen de la antropóloga Virginia Gutiérrez")
  elif bi == "4":
    print("Este billete rinde homenaje al presidente de Colombia Alfonso López Michelsen")
  elif bi == "5":
    print("Este billete rinde homenaje al nobel de literatura Gabriel García Márquez")
  elif bi == "6":
    print("En el anverso se aprecia la imagen del presidente Carlos Lleras Restrepo")

dinero()

lista1 = [3, 5, 1, 9, 10, 11, 32, 21, 5, 1, 209, 432, 1, 32, 45]

lista1.append(10)

lista1

lista1.append(3)

lista1

lista1.extend([5,6,7])

lista1

lista1.remove(7)

lista1.sort()

lista1

lista1.remove(432)

lista1

lista1.reverse()

lista1

lista1.pop(10)

lista1

lista1.append(10)

lista1

lista1.append(345)

lista1.append(1)

lista1

lista1.pop(8)

lista1

lista1.reverse()

lista1

lista1.sort()

lista1

for i in lista1:
  if ((i % 2 == 0)**2):
    print(i**2)

for i in lista1:
  if i % 3 == 0:
    print(i**3)

lista1

lista1.remove(345)

lista1.remove(209)

lista1

