# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I6FwlSM-x5eYhHIP7MNbiDZQAMmplQwt
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import chi2_contingency
import statsmodels.api as sm

from scipy.stats import mode

df = pd.read_csv("datos_whales.csv")

df.info()

df = df[["SeeWhales","Education","Age","Income", "PayConserve", "Income_AUD"]]

df.describe()

df.mean()

df["Age"] = df["Age"].fillna(42.918958)

df

y = pd.crosstab(df["Education"], df["PayConserve"])

chi2_contingency(y)

"""No hay relación entre educación y Pay Conserve, debido a que el valor P es mayor de 0.05"""

u = pd.crosstab(df["Income_AUD"], df["PayConserve"])

chi2_contingency(u)

"""Si hay relación entre la variable Income_AUD y Pay Conserve, debido a que el valor P es menor de 0.05"""

ballena = pd.crosstab(df["SeeWhales"], df["PayConserve"])

chi2_contingency(ballena)

"""Si hay relación entre la variable SeeWhales (Ver ballenas) y Pay Conserve, debido a que el valor P es menor de 0.05"""

edad = pd.crosstab(df["Age"], df["PayConserve"])

chi2_contingency(edad)

"""No hay relación entre la edad y Pay Conserve, debido a que el valor P es mayor de 0.05"""

df

df["Income"] = df["Income"].fillna(44540.456973)

df

af = df.drop(columns=["Income_AUD", "Education"])

df

y = af["PayConserve"]
x = af[["SeeWhales", "Age","Income"]]
x = sm.add_constant(x)
model = sm.OLS(y,x)
reg = model.fit()
reg.summary()

"""- Una unidad adicional en See Whales (Ver ballenas) incrementa en un 0.15 la probabilidad en la disposición a pagar dos dolares para proteger el habitat.

- Una unidad adcional en la edad disminuye la probabilidad en un 0,3 la probabilidad en la disposición a pagar dos dolares para proteger el habitat.

- Una unidad adicional en el ingrese disminuye la probabilidad en un -4.796e-0la disposición a pagar dos dolares para proteger el habitat.

- Las varaibles significativas son: See Whales (Ver ballenas), edad, el ingreso, y las que no son significativas: el ingreso
"""

